---
title: "LSTAT2150 — Nonparametric Statistics (Smoothing Methods):Project on variance estimation for non-parametric regression"
author: "zeamari yassine"
date: "11/23/2024"
output:
  pdf_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.path = 'figures/',
  dev = 'pdf'
)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
getwd()
```



# la simulation deux méthodes:

**A.analyse par region**
```{r }
set.seed(123) 
m <- function(x) (sin(2 * pi * x^3))^3
sigma2 <- function(x) 2 + sin(2 * pi * x)


simulation_data <- function(n) {
  X <- seq(1/n, 1, length.out = n) # Xi = i/n
 
  Y <- m(X)+rnorm(n,0,0.5*sqrt(sigma2(X)))
  return(list(X = X, Y = Y))
}

    
gaussian_kernel <-function(u) dnorm(u)

kernel_estimate <- function(x, X, Y, h) {
  weights <- gaussian_kernel((X - x) / h)
  sum(weights * Y) / sum(weights)
  
}

```

```{r}
m_estimate <- function(x, X, Y, h) {      #estimation m
  sapply(x, function(xi) kernel_estimate(xi, X, Y, h))
}
#estimation méthode residual
estimate_sigma2_residual <- function(x, X, Y, h_m,h_sigma) { 
  m_hat <- m_estimate(X, X, Y, h_m) # Estimation de m(X)
  residuals <- (Y - m_hat)^2
  sapply(x, function(xi) kernel_estimate(xi, X, residuals, h_sigma))

}
```

```{r}
#estimation méthode directe
estimate_sigma2_direct <- function(x, X, Y, h_m,h_sigma) {
  EY2_hat <- sapply(x, function(xi) kernel_estimate(xi, X, Y^2, h_sigma)) # E[Y^2 | X=x]
  m_hat <- m_estimate(x, X, Y, h_m) # m(x)
  EY2_hat - m_hat^2
}
```

```{r}
h_m=0.1#h_1
h_sigma=0.1#h_2
x_p=seq(from = 0, to = 1, length = 100)
k=400
n=100
 resultat1=matrix(NA, nrow = k, ncol = length(x_p)) 
 resultat2=matrix(NA, nrow = k, ncol = length(x_p))
 for (i in 1:k){
    
    data <- simulation_data(n)
    X <- data$X
    Y <- data$Y
    
    sigma2_con=estimate_sigma2_direct(x_p,X,Y,h_m,h_sigma)
    
    sigma2_res=estimate_sigma2_residual(x_p,X,Y,h_m,h_sigma)
    resultat1[i, ] =sigma2_con
    resultat2[i,]=sigma2_res
    
 }
 
```

```{r}
# Vraies valeurs de sigma^2(x)
true_sigma2 <- sigma2(x_p)

# Moyenne des estimations Monte Carlo
mean_estimation1 <- colMeans(resultat1)/0.25

mean_estimation2 <- colMeans(resultat2)/0.25




# Graphique des résultats
library(ggplot2)

# Préparation des données pour ggplot
plot_data <- data.frame(
  x = rep(x_p, 3),
  value = c(true_sigma2, mean_estimation1, mean_estimation2),
  Type = rep(c("True Sigma^2", "Mean Estimation conditionnel", "Mean Estimation résiduel"), each = length(x_p))
)


# Tracer
ggplot(plot_data, aes(x = x, y = value, color = Type, linetype = Type)) +
  geom_line(size = 1) +
  labs(title = "Comparison of True and Estimated Variance",
       x = "x",
       y = expression(sigma^2(x)),
       color = "Type",
       linetype = "Type") +
  theme_minimal() +
  theme(legend.position = "top")

```



**B.analyse des performonces**


```{r}
# ce code pour calculer et tracer mse
# Vraies valeurs de sigma^2(x)
true_sigma2 <- sigma2(x_p)

# Moyenne des estimations Monte Carlo
mean_estimation1 <- colMeans(resultat1)/0.25

mean_estimation2 <- colMeans(resultat2)/0.25
biais_directe=mean_estimation1 - true_sigma2
biais_residualle=mean_estimation2 - true_sigma2
variance_directe <- apply(resultat1, 2, function(x) (length(x) - 1) / length(x) * var(x))
variance_residualle <- apply(resultat2, 2, function(x) (length(x) - 1) / length(x) * var(x))

mse_directe=biais_directe^2 + variance_directe
mse_residualle=biais_residualle^2 +variance_residualle

plot(x_p,mse_directe, type="l", col="red", 
     xlab="x", ylab="MSE")
lines(x_p,mse_residualle, col="blue")
legend("topright",
       legend=c("MSE direct", "MSE résiduel"),
       col=c("red", "blue"),
       lty=1,
       cex=0.7)
mtext("MSE des estimateurs", outer = TRUE, cex = 0.6)
```


```{r}
#ce code calcule et print le bias et la variance et mse au points interessants (table 1)
set.seed(130)
x_interest <- c(0.01, 0.25, 0.75, 1)
k <- 400  # nombre de répétitions Monte Carlo
h_m <- 0.1
h_sigma <- 0.1

calculate_metrics <- function(n, x_point) {
    results_direct <- numeric(k)
    results_residual <- numeric(k)
    true_value <- sigma2(x_point)
    
    for(i in 1:k) {
        data <- simulation_data(n)
        X <- data$X
        Y <- data$Y
        
        # Calcul pour un seul point x_point
        sigma2_direct <- estimate_sigma2_direct(x_point, X, Y, h_m, h_sigma)
        sigma2_residual <- estimate_sigma2_residual(x_point, X, Y, h_m, h_sigma)
        
        # Stockage des résultats pour ce point
        results_direct[i] <- sigma2_direct
        results_residual[i] <- sigma2_residual
    }
    
    # Calcul des métriques
    mean_direct <- mean(results_direct)/0.25
    mean_residual <- mean(results_residual)/0.25
    
    biais_direct <- mean_direct - true_value
    biais_residual <- mean_residual - true_value
    
    # Correction du calcul de la variance
    variance_direct <- var(results_direct)
    variance_residual <- var(results_residual)
    
    mse_direct <- biais_direct^2 + variance_direct
    mse_residual <- biais_residual^2 + variance_residual
    
    return(list(
        bias = c(direct = biais_direct, residual = biais_residual),
        variance = c(direct = variance_direct, residual = variance_residual),
        mse = c(direct = mse_direct, residual = mse_residual)
    ))
}

# Analyse pour chaque point d'intérêt
for(x in x_interest) {
    metrics <- calculate_metrics(n = 100, x)
    cat("\nAnalyse au point x =", x, "\n")
    cat("Biais:", "\nDirect:", round(metrics$bias["direct"], 4),
        "\nResiduel:", round(metrics$bias["residual"], 4), "\n")
    cat("Variance:", "\nDirect:", round(metrics$variance["direct"], 4),
        "\nResiduel:", round(metrics$variance["residual"], 4), "\n")
    cat("MSE:", "\nDirect:", round(metrics$mse["direct"], 4),
        "\nResiduel:", round(metrics$mse["residual"], 4), "\n")
}

```


# Étude de la sensibilité aux paramètres de lissage



## l'évolution des estimateurs en fonction des différentes valeurs de $h_1$ en fixant $h_2$

```{r}
#ce code trace 6 graphes l'evolution de deux méthodes en fonction des valeurs h_1
h_sigma=0.1
resultats_direct_hm <- list()
resultats_residual_hm <- list()
h=c(0.02,0.04,0.08,0.1,0.15,0.2)
for(h_m in h ){
  
  
 resultat1=matrix(NA, nrow = k, ncol = length(x_p)) 
 resultat2=matrix(NA, nrow = k, ncol = length(x_p))
 for (i in 1:k){
    
    data <- simulation_data(n)
    X <- data$X
    Y <- data$Y
    
    sigma2_con=estimate_sigma2_direct(x_p,X,Y,h_m,h_sigma)
    
    sigma2_res=estimate_sigma2_residual(x_p,X,Y,h_m,h_sigma)
    resultat1[i, ] =sigma2_con
    resultat2[i,]=sigma2_res
  
 } 
 resultats_direct_hm[[as.character(h_m)]]=colMeans(resultat1)/0.25
 resultats_residual_hm[[as.character(h_m)]] =colMeans(resultat2)/0.25
 
}
true_sigma2 <- sigma2(x_p)


# Tracer les résultats pour les variations de h_sigma (h_m fixé)


par(mfrow = c(3, 2), # 3 rangées et 2 colonnes
    mar = c(4, 4, 2, 2) + 0.1, # Marges des graphiques
    oma = c(2, 2, 2, 2))
for (h_m in names(resultats_direct_hm)) {
  plot(x_p, true_sigma2, type = "l", col = "black", lty = 2,
       ylim = range(c(true_sigma2, unlist(resultats_direct_hm), unlist(resultats_residual_hm))),
       main = paste("h_1 =", h_m, ", h_2 =", h_sigma),
       xlab = "x", ylab = "sigma^2(x)")
  lines(x_p, resultats_direct_hm[[h_m]], col = "blue")
  lines(x_p, resultats_residual_hm[[h_m]], col = "red")
  legend("topright", legend = c("True", "Direct", "Residual"),
         col = c("black", "blue", "red"), lty = c(2, 1, 1), bty = "n")
}

mtext("Impact of h_1 and h_2 on Variance Estimation", outer = TRUE, cex = 0.6)
```


## l'évolution des estimateurs en fonction des différentes valeurs de $h_2$ en fixant $h_1 =0.1$

```{r}
#ce code trace 6 graphes l'evolution de deux méthodes en fonction des valeurs h_2

h_m=0.1#h_1
resultats_direct_hsigma <- list()
resultats_residual_hsigma <- list()
h=c(0.02,0.04,0.08,0.1,0.15,0.2)
for(h_sigm in h ){
  
  
 resultat1=matrix(NA, nrow = k, ncol = length(x_p)) 
 resultat2=matrix(NA, nrow = k, ncol = length(x_p))
 for (i in 1:k){
    
    data <- simulation_data(n)
    X <- data$X
    Y <- data$Y
    
    sigma2_con=estimate_sigma2_direct(x_p,X,Y,h_m,h_sigm)
    
    sigma2_res=estimate_sigma2_residual(x_p,X,Y,h_m,h_sigm)
    resultat1[i,] =sigma2_con
    resultat2[i,]=sigma2_res
  
 } 
 resultats_direct_hsigma[[as.character(h_sigm)]]=colMeans(resultat1)/0.25
 resultats_residual_hsigma[[as.character(h_sigm)]] =colMeans(resultat2)/0.25
 
}
true_sigma2 <- sigma2(x_p)


# Tracer les résultats pour les variations de h_sigma (h_m fixé)


par(mfrow = c(3, 2), # 3 rangées et 2 colonnes
    mar = c(4, 4, 2, 2) + 0.1, # Marges des graphiques
    oma = c(2, 2, 2, 2))
for (h_sigm in names(resultats_direct_hsigma)) {
  plot(x_p, true_sigma2, type = "l", col = "black", lty = 2,
       ylim = range(c(true_sigma2, unlist(resultats_direct_hsigma), unlist(resultats_residual_hsigma))),
       main = paste("h_1 =", h_m, ", h_2 =", h_sigm),
       xlab = "x", ylab = "sigma^2(x)")
  lines(x_p, resultats_direct_hsigma[[h_sigm]], col = "blue")
  lines(x_p, resultats_residual_hsigma[[h_sigm]], col = "red")
  legend("topright", legend = c("True", "Direct", "Residual"),
         col = c("black", "blue", "red"), lty = c(2, 1, 1), bty = "n")
}

mtext("Impact of h_1 and h_2 on Variance Estimation", outer = TRUE, cex = 0.6)
```


# étude asymptotique


```{r}
#ce code Calcule et trace les biais, variances et MSE moyens pour chaque taille n

n_values <- c(25, 50, 100, 500, 1000) # Tailles croissantes d'échantillons
h_m <- 0.08
h_sigma <- 0.08
x_p <- seq(0, 1, length = 100) # Points d'évaluation
k <- 400 # Répétitions Monte Carlo


# Stocker les résultats
results_asymptotic <- list()
mean_estm= list()

for (n in n_values) {
  
  resultat1 <- matrix(NA, nrow = k, ncol = length(x_p)) 
  resultat2 <- matrix(NA, nrow = k, ncol = length(x_p))
  
  for (i in 1:k) {
    data <- simulation_data(n)
    X <- data$X
    Y <- data$Y
    
    # Calculs des deux estimateurs
    sigma2_direct <- estimate_sigma2_direct(x_p, X, Y, h_m, h_sigma)
    sigma2_residual <- estimate_sigma2_residual(x_p, X, Y, h_m, h_sigma)
    
    # Stockage des résultats
    resultat1[i, ] <- sigma2_direct
    resultat2[i, ] <- sigma2_residual
  }
  
 true_sigma2 <- sigma2(x_p)

mean_estimation1 <- colMeans(resultat1)/0.25
mean_estimation2 <- colMeans(resultat2)/0.25

biais_direct=mean_estimation1 - true_sigma2
biais_residual=mean_estimation2 - true_sigma2
variance_direct <- apply(resultat1, 2, function(x) (length(x) - 1) / length(x) * var(x))
variance_residual <- apply(resultat2, 2, function(x) (length(x) - 1) / length(x) * var(x))

mse_direct=biais_direct^2 + variance_direct
mse_residual=biais_residual^2 +variance_residual

  mean_estm[[as.character(n)]]=list(
    mean_estimation1=mean_estimation1,
    mean_estimation2=mean_estimation2
  )
 
  # Stocker les résultats pour chaque taille d'échantillon
  results_asymptotic[[as.character(n)]] <- list(
    biais_direct = biais_direct,
    biais_residual = biais_residual,
    variance_direct = variance_direct,
    variance_residual = variance_residual,
    mse_direct = mse_direct,
    mse_residual = mse_residual
  )
}

# Calculer les biais, variances et MSE moyens pour chaque taille n
biais_direct_mean <- sapply(results_asymptotic, function(res) mean(res$biais_direct))
biais_residual_mean <- sapply(results_asymptotic, function(res) mean(res$biais_residual))

variance_direct_mean <- sapply(results_asymptotic, function(res) mean(res$variance_direct))
variance_residual_mean <- sapply(results_asymptotic, function(res) mean(res$variance_residual))

mse_direct_mean <- sapply(results_asymptotic, function(res) mean(res$mse_direct))
mse_residual_mean <- sapply(results_asymptotic, function(res) mean(res$mse_residual))

# Disposer les graphiques : une ligne, trois colonnes
par(mfrow = c(1, 3))

# Calcul des limites des axes
ylim_biais <- range(c(abs(biais_direct_mean), abs(biais_residual_mean)), na.rm = TRUE)
ylim_variance <- range(c(variance_direct_mean, variance_residual_mean), na.rm = TRUE)
ylim_mse <- range(c(mse_direct_mean, mse_residual_mean), na.rm = TRUE)

# 1. Graphique pour le biais moyen
plot(n_values, abs(biais_direct_mean), type = "b", col = "blue", log = "y",
     ylim = ylim_biais,
     xlab = "n", ylab = "Biais moyen", main = "Biais moyen")
lines(n_values, abs(biais_residual_mean), type = "b", col = "red")
legend("topright", legend = c("Direct", "Residual"), col = c("blue", "red"), lty = 1, bty = "n")

# 2. Graphique pour la variance moyenne
plot(n_values, variance_direct_mean, type = "b", col = "blue", log = "y",
     ylim = ylim_variance,
     xlab = "n", ylab = "Variance moyenne", main = "Variance moyenne")
lines(n_values, variance_residual_mean, type = "b", col = "red")
legend("topright", legend = c("Direct", "Residual"), col = c("blue", "red"), lty = 1, bty = "n")

# 3. Graphique pour le MSE moyen
plot(n_values, mse_direct_mean, type = "b", col = "blue", log = "y",
     ylim = ylim_mse,
     xlab = "n", ylab = "MSE moyen", main = "MSE moyen")
lines(n_values, mse_residual_mean, type = "b", col = "red")
legend("topright", legend = c("Direct", "Residual"), col = c("blue", "red"), lty = 1, bty = "n")

```

```{r}
#ce code  trace deux méthodes pour chaque taille n

n_values <- c(25, 50, 100, 500, 1000)
# Définir les couleurs
colors <- rainbow(length(n_values))

# Tracer la vraie fonction
plot(x_p, sigma2(x_p), type = "l", lwd = 2, col = "black",
     main = "Estimateur Direct pour différentes tailles d'échantillon",
     xlab = "x", ylab = "sigma²(x)", ylim = c(0, 4))

# Ajouter les estimations moyennes pour chaque taille d'échantillon
legend_text <- c("Vraie fonction")
legend_colors <- c("black")

for (i in seq_along(n_values)) {
  n <- n_values[i]
  
  # Ajouter la courbe pour la taille d'échantillon correspondante
  lines(x_p, mean_estm[[as.character(n)]]$mean_estimation1, col = colors[i], lty = 2)
  
  # Mettre à jour la légende
  legend_text <- c(legend_text, paste("n =", n))
  legend_colors <- c(legend_colors, colors[i])
}

# Ajouter la légende
legend("bottomleft", legend = legend_text, col = legend_colors, lty = c(1, rep(2, length(n_values)), inset = c(0.04, 0.01)))

plot(x_p, sigma2(x_p), type = "l", lwd = 2, col = "black",
          main = "Estimateur résiduelle pour différentes tailles d'échantillon",
     xlab = "x", ylab = "sigma²(x)", ylim = c(0, 4))

# Ajouter les estimations moyennes pour chaque taille d'échantillon
legend_text <- c("Vraie fonction")
legend_colors <- c("black")

for (i in seq_along(n_values)) {
  n <- n_values[i]
  
  # Ajouter la courbe pour la taille d'échantillon correspondante
  lines(x_p, mean_estm[[as.character(n)]]$mean_estimation2, col = colors[i], lty = 2)
  
  # Mettre à jour la légende
  legend_text <- c(legend_text, paste("n =", n))
  legend_colors <- c(legend_colors, colors[i])
}

# Ajouter la légende
legend("topright", legend = legend_text, col = legend_colors, lty = c(1, rep(2, length(n_values))))

```

